platform :ios, ‘8.0’

target 'SimpleApp' do

pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2' #第三方约束
pod 'IQKeyboardManager', '~> 4.0.10' #键盘遮挡控件
pod 'BlocksKit', '~> 2.2.5' #block扩展
pod 'MBProgressHUD' #hud
pod 'SDWebImage', '~> 4.0.0' #图片下载
pod 'MJRefresh' #下拉刷新
pod 'OpenUDID'
pod 'ReactiveCocoa', '~> 2.5'
pod 'YYKit', '~> 1.0.9'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMapNavi'
pod 'RNTimer'
pod "RTRootNavigationController"
pod 'MJRefresh'
end
